/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package group6bscs22;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.*;
import java.util.Map;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Raffy
 */
public class TablesForm extends javax.swing.JFrame {
    private Connection conn = null;
    private PreparedStatement ps = null;
    private ResultSet rs = null;
    private final String db = "jdbc:mysql://localhost/oop_activity";
    private final Map<String, String> env = System.getenv();
    private final Dimension resolution = Toolkit.getDefaultToolkit().getScreenSize();

    /**
     * Creates new form TablesForm
     */
    public TablesForm() {
        preInit();
        initComponents();
        postInit();
    }

    private void preInit(){
        conn = ConnectDB.connect(db, env.get("mysqluser"), env.get("mysqlpass"));
    }
    private void postInit(){
        this.setLocation((resolution.width - this.getSize().width) / 2, 
                (resolution.height - this.getSize().height) / 2);
        tblMain.setDefaultEditor(Object.class, null);
        
        Vector<String> tables = new Vector<>();
        try{
            ps = conn.prepareStatement("SHOW TABLES");
            rs = ps.executeQuery();
            
            while(rs.next()){
                tables.add(rs.getString(1).toUpperCase());
            }
            listTables.setModel(new DefaultComboBoxModel<String>(tables));
            showTable();
        }catch(Exception e){
            System.out.println(e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void showTable(){
        String currentTable = listTables.getSelectedItem().toString();
        try{
            ps = conn.prepareStatement("SELECT * FROM " + currentTable);
            rs = ps.executeQuery();
            ResultSetMetaData metadata = rs.getMetaData();
            tblMain.setModel(DbUtils.resultSetToTableModel(rs));
            
            lblField1.setText(metadata.getColumnName(1)
                    .replaceAll("_", " "));
            lblField2.setText(metadata.getColumnName(2)
                    .replaceAll("_", " "));
            lblField3.setText(metadata.getColumnName(3)
                    .replaceAll("_", " "));
            lblField4.setText(metadata.getColumnName(4)
                    .replaceAll("_", " "));
            lblField5.setText(metadata.getColumnName(5)
                    .replaceAll("_", " "));
            
        }catch(Exception e){
            System.out.println(e);
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLeft = new javax.swing.JPanel();
        listTables = new javax.swing.JComboBox<>();
        lblField1 = new javax.swing.JLabel();
        lblField2 = new javax.swing.JLabel();
        lblField3 = new javax.swing.JLabel();
        lblField4 = new javax.swing.JLabel();
        lblField5 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMain = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("College Records");
        setBackground(new java.awt.Color(255, 215, 0));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        panelLeft.setBackground(new java.awt.Color(128, 0, 0));
        panelLeft.setForeground(new java.awt.Color(255, 255, 255));

        listTables.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        listTables.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        listTables.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listTablesItemStateChanged(evt);
            }
        });
        listTables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listTablesActionPerformed(evt);
            }
        });

        lblField1.setBackground(new java.awt.Color(255, 255, 255));
        lblField1.setForeground(new java.awt.Color(255, 255, 255));
        lblField1.setText("COLLEGE CODE");

        lblField2.setForeground(new java.awt.Color(255, 255, 255));
        lblField2.setText("DESCRIPTION");

        lblField3.setForeground(new java.awt.Color(255, 255, 255));
        lblField3.setText("ACTIVE");

        lblField4.setForeground(new java.awt.Color(255, 255, 255));
        lblField4.setText("DATE OPENED");

        lblField5.setForeground(new java.awt.Color(255, 255, 255));
        lblField5.setText("DATE CLOSED");

        btnAdd.setBackground(new java.awt.Color(204, 204, 204));
        btnAdd.setForeground(new java.awt.Color(0, 0, 0));
        btnAdd.setText("Add");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(204, 204, 204));
        btnUpdate.setForeground(new java.awt.Color(0, 0, 0));
        btnUpdate.setText("Update");
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(204, 204, 204));
        btnDelete.setForeground(new java.awt.Color(0, 0, 0));
        btnDelete.setText("Delete");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Current Table");

        javax.swing.GroupLayout panelLeftLayout = new javax.swing.GroupLayout(panelLeft);
        panelLeft.setLayout(panelLeftLayout);
        panelLeftLayout.setHorizontalGroup(
            panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLeftLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLeftLayout.createSequentialGroup()
                            .addGroup(panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblField3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblField4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblField2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblField5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField4)
                                .addComponent(jTextField3)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(148, 148, 148))
                        .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLeftLayout.createSequentialGroup()
                            .addComponent(btnAdd)
                            .addGap(31, 31, 31)
                            .addComponent(btnUpdate)
                            .addGap(28, 28, 28)
                            .addComponent(btnDelete)
                            .addGap(35, 35, 35)))
                    .addComponent(listTables, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
            .addGroup(panelLeftLayout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelLeftLayout.setVerticalGroup(
            panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLeftLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listTables, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblField1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblField2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblField3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblField4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblField5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addGap(75, 75, 75))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        tblMain.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblMain.setGridColor(new java.awt.Color(255, 255, 255));
        tblMain.setRowHeight(45);
        tblMain.setRowMargin(3);
        tblMain.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tblMain.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tblMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMainMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMain);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 215, 0));
        jPanel2.setForeground(new java.awt.Color(255, 251, 0));
        jPanel2.setFocusable(false);
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        showTable();
    }//GEN-LAST:event_formWindowActivated

    private void tblMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMainMouseClicked
        // TODO add your handling code here:
        int row = tblMain.getSelectedRow();
        try{
            ps = conn.prepareStatement("SELECT * FROM " + listTables.getSelectedItem().toString());
            rs = ps.executeQuery();
            while(rs.next()){
                jTextField1.setText(tblMain.getValueAt(row, 0).toString());
                jTextField2.setText(tblMain.getValueAt(row, 1).toString());
                jTextField3.setText(tblMain.getValueAt(row, 2).toString());
                jTextField4.setText(tblMain.getValueAt(row, 3).toString());
                jTextField5.setText(tblMain.getValueAt(row, 4).toString());
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, e, "Error", JOptionPane.ERROR);
        }
    }//GEN-LAST:event_tblMainMouseClicked

    private void clearTextFields(){
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
    }
    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        // TODO add your handling code here:
        int answer = JOptionPane.showConfirmDialog(this, "Do you really want to delete?", "Delete", JOptionPane.YES_NO_OPTION);
        if(answer != 0){
            JOptionPane.showMessageDialog(this, "Aborted update of record", "Abort",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        try{
            if(listTables.getSelectedItem().toString().equals("COLLEGE"))
            ps = conn.prepareStatement("DELETE FROM COLLEGE "
                + "WHERE COLLEGE_CODE = ?");

            else
            ps = conn.prepareStatement("DELETE FROM SUBJECT "
                + "WHERE SUBJECT_CODE = ?");

            ps.setString(1, jTextField1.getText());
            ps.executeUpdate();
            clearTextFields();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        // TODO add your handling code here:
        int answer = JOptionPane.showConfirmDialog(this, "Do you really want to update?", "Update",JOptionPane.YES_NO_OPTION);
        if(answer != 0){
            JOptionPane.showMessageDialog(this, "Aborted update of record", "Abort",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        try{
            if(listTables.getSelectedItem().toString().equals("COLLEGE")){
                ps = conn.prepareStatement("UPDATE COLLEGE "
                    + "SET DESCRIPTION = ?, ACTIVE = ?, DATE_OPENED = ?, DATE_CLOSED = ? "
                    + "WHERE COLLEGE_CODE = ?");

                ps.setString(2, jTextField3.getText().toUpperCase());
                ps.setDate(3, Date.valueOf(jTextField4.getText()));
                ps.setDate(4, Date.valueOf(jTextField5.getText()));
            }
            else{
                ps = conn.prepareStatement("UPDATE SUBJECT "
                    + "SET DESCRIPTION = ?, UNITS = ?, COLLEGE_CODE = ?, ACTIVE = ? "
                    + "WHERE SUBJECT_CODE = ?");
                ps.setInt(2, Integer.valueOf(jTextField3.getText()));
                ps.setString(3, jTextField4.getText());
                ps.setString(4, jTextField5.getText().toUpperCase());
            }
            ps.setString(1, jTextField2.getText());
            ps.setString(5, jTextField1.getText());

            ps.executeUpdate();

        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        // TODO add your handling code here:
        int answer = JOptionPane.showConfirmDialog(this, "Do you really want to add?", "Add", JOptionPane.YES_NO_OPTION);
        if(answer != 0){
            JOptionPane.showMessageDialog(this, "Aborted insertion of record", "Abort",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        try{
            if(listTables.getSelectedItem().toString().equals("COLLEGE")){
                ps = conn.prepareStatement("INSERT INTO COLLEGE VALUES(?, ?, ?, ?, ?)");
                ps.setString(3, jTextField3.getText().toUpperCase());
                ps.setDate(4, Date.valueOf(jTextField4.getText()));
                ps.setDate(5, Date.valueOf(jTextField5.getText()));
            }
            else{
                ps = conn.prepareStatement("INSERT INTO SUBJECT VALUES (?, ?, ?, ?, ?)");
                ps.setInt(3, Integer.valueOf(jTextField3.getText()));
                ps.setString(4, jTextField4.getText());
                ps.setString(5, jTextField5.getText().toUpperCase());
            }

            ps.setString(1, jTextField1.getText());
            ps.setString(2, jTextField2.getText());

            ps.executeUpdate();

        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddMouseClicked

    private void listTablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listTablesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listTablesActionPerformed

    private void listTablesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listTablesItemStateChanged
        // TODO add your handling code here:
        showTable();
        clearTextFields();
    }//GEN-LAST:event_listTablesItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablesForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel lblField1;
    private javax.swing.JLabel lblField2;
    private javax.swing.JLabel lblField3;
    private javax.swing.JLabel lblField4;
    private javax.swing.JLabel lblField5;
    private javax.swing.JComboBox<String> listTables;
    private javax.swing.JPanel panelLeft;
    private javax.swing.JTable tblMain;
    // End of variables declaration//GEN-END:variables
}
