/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package group6bscs22;
import javax.swing.*;
import java.sql.*;
import java.util.Map;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Raffy
 */
public class TableFrame extends javax.swing.JFrame {
    private Connection conn = null;
    private PreparedStatement ps = null;
    private ResultSet rs = null;
    private final String db = "jdbc:mysql://localhost/oop_activity";
    private final Map<String, String> env = System.getenv();
    /**
     * Creates new form TableFrame
     */
    public TableFrame() {
        preInit();
        initComponents();
        postInit();
    }
    private void preInit(){
        conn = ConnectDB.connect(db, env.get("mysqluser"), env.get("mysqlpass"));
    }
    private void postInit(){
        tblCollege.setDefaultEditor(Object.class, null);
        tblSubject.setDefaultEditor(Object.class, null);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        panelCollege = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCollege = new javax.swing.JTable();
        lblCollegeCode = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        lblActive = new javax.swing.JLabel();
        lblDateOpened = new javax.swing.JLabel();
        lblDateClosed = new javax.swing.JLabel();
        txtCollegeCode = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        txtActive = new javax.swing.JTextField();
        txtDateOpened = new javax.swing.JTextField();
        txtDateClosed = new javax.swing.JTextField();
        btnCollegeAdd = new javax.swing.JButton();
        btnCollegeUpdate = new javax.swing.JButton();
        btnCollegeDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        panelSubject = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSubject = new javax.swing.JTable();
        lblSubjectCode = new javax.swing.JLabel();
        lblSubDescription = new javax.swing.JLabel();
        lblUnits = new javax.swing.JLabel();
        lblCollegeCodeFK = new javax.swing.JLabel();
        lblSubActive = new javax.swing.JLabel();
        txtSubjectCode = new javax.swing.JTextField();
        txtSubDescription = new javax.swing.JTextField();
        txtUnits = new javax.swing.JTextField();
        txtCollegeCodeFK = new javax.swing.JTextField();
        txtSubActive = new javax.swing.JTextField();
        btnSubAdd = new javax.swing.JButton();
        btnSubUpdate = new javax.swing.JButton();
        btnSubDelete = new javax.swing.JButton();
        btnSubClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        tabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabbedPaneStateChanged(evt);
            }
        });

        tblCollege.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCollege.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCollegeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCollege);

        lblCollegeCode.setText("College Code");

        lblDescription.setText("Description");

        lblActive.setText("Active");

        lblDateOpened.setText("Date Opened");

        lblDateClosed.setText("Date Closed");

        btnCollegeAdd.setText("Add");
        btnCollegeAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCollegeAddMouseClicked(evt);
            }
        });

        btnCollegeUpdate.setText("Update");
        btnCollegeUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCollegeUpdateMouseClicked(evt);
            }
        });

        btnCollegeDelete.setText("Delete");
        btnCollegeDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCollegeDeleteMouseClicked(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelCollegeLayout = new javax.swing.GroupLayout(panelCollege);
        panelCollege.setLayout(panelCollegeLayout);
        panelCollegeLayout.setHorizontalGroup(
            panelCollegeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCollegeLayout.createSequentialGroup()
                .addGroup(panelCollegeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCollegeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(panelCollegeLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelCollegeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCollegeLayout.createSequentialGroup()
                                .addGroup(panelCollegeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDescription)
                                    .addComponent(lblActive)
                                    .addComponent(lblDateOpened)
                                    .addComponent(lblDateClosed))
                                .addGap(19, 19, 19)
                                .addGroup(panelCollegeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtActive, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelCollegeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtDateClosed, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                        .addComponent(txtDateOpened, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelCollegeLayout.createSequentialGroup()
                                .addComponent(lblCollegeCode)
                                .addGap(18, 18, 18)
                                .addComponent(txtCollegeCode, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnClear)
                                .addGap(163, 163, 163)))))
                .addContainerGap())
            .addGroup(panelCollegeLayout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(btnCollegeAdd)
                .addGap(47, 47, 47)
                .addComponent(btnCollegeUpdate)
                .addGap(48, 48, 48)
                .addComponent(btnCollegeDelete)
                .addContainerGap(330, Short.MAX_VALUE))
        );
        panelCollegeLayout.setVerticalGroup(
            panelCollegeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCollegeLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelCollegeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCollegeCode)
                    .addComponent(txtCollegeCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCollegeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescription)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCollegeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblActive)
                    .addComponent(txtActive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCollegeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateOpened)
                    .addComponent(txtDateOpened, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(panelCollegeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateClosed)
                    .addComponent(txtDateClosed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(panelCollegeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCollegeAdd)
                    .addComponent(btnCollegeUpdate)
                    .addComponent(btnCollegeDelete))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabbedPane.addTab("College", panelCollege);

        tblSubject.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSubject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSubjectMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSubject);

        lblSubjectCode.setText("Subject Code");

        lblSubDescription.setText("Description");

        lblUnits.setText("Units");

        lblCollegeCodeFK.setText("College Code");

        lblSubActive.setText("Active");

        btnSubAdd.setText("Add");
        btnSubAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubAddMouseClicked(evt);
            }
        });

        btnSubUpdate.setText("Update");
        btnSubUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubUpdateMouseClicked(evt);
            }
        });

        btnSubDelete.setText("Delete");
        btnSubDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubDeleteMouseClicked(evt);
            }
        });

        btnSubClear.setText("Clear");
        btnSubClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubClearMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelSubjectLayout = new javax.swing.GroupLayout(panelSubject);
        panelSubject.setLayout(panelSubjectLayout);
        panelSubjectLayout.setHorizontalGroup(
            panelSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSubjectLayout.createSequentialGroup()
                .addGroup(panelSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSubjectLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(panelSubjectLayout.createSequentialGroup()
                        .addGroup(panelSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelSubjectLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(panelSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSubActive)
                                    .addComponent(lblSubjectCode)
                                    .addComponent(lblUnits)
                                    .addComponent(lblSubDescription))
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSubjectLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblCollegeCodeFK)
                                .addGap(18, 18, 18)))
                        .addGroup(panelSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelSubjectLayout.createSequentialGroup()
                                .addGroup(panelSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSubDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUnits, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCollegeCodeFK, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSubActive, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelSubjectLayout.createSequentialGroup()
                                .addComponent(txtSubjectCode, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(244, 244, 244)
                        .addComponent(btnSubClear)
                        .addGap(158, 158, 158)))
                .addContainerGap())
            .addGroup(panelSubjectLayout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(btnSubAdd)
                .addGap(49, 49, 49)
                .addComponent(btnSubUpdate)
                .addGap(46, 46, 46)
                .addComponent(btnSubDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSubjectLayout.setVerticalGroup(
            panelSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSubjectLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panelSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubjectCode)
                    .addGroup(panelSubjectLayout.createSequentialGroup()
                        .addGroup(panelSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSubjectCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSubClear))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSubDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSubDescription))
                        .addGap(18, 18, 18)
                        .addGroup(panelSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUnits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUnits))
                        .addGap(18, 18, 18)
                        .addGroup(panelSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCollegeCodeFK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCollegeCodeFK))
                        .addGap(6, 6, 6)
                        .addGroup(panelSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSubActive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSubActive))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(panelSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubAdd)
                    .addComponent(btnSubUpdate)
                    .addComponent(btnSubDelete))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabbedPane.addTab("Subject", panelSubject);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void displayTable(){
        int selected = tabbedPane.getSelectedIndex();
        if(selected == -1){
            JOptionPane.showMessageDialog(tabbedPane, "Invalid index error", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        this.setTitle(tabbedPane.getTitleAt(selected) + " Records");
        try{
            switch(selected){
                case 0:
                    ps = conn.prepareStatement("SELECT * FROM COLLEGE");
                    rs = ps.executeQuery();
                    tblCollege.setModel(DbUtils.resultSetToTableModel(rs));
                    break;
                case 1:
                    ps = conn.prepareStatement("SELECT * FROM SUBJECT");
                    rs = ps.executeQuery();
                    tblSubject.setModel(DbUtils.resultSetToTableModel(rs));
                    break;
                default:
                    JOptionPane.showMessageDialog(tabbedPane, "Unhandled case", "Error", JOptionPane.ERROR_MESSAGE);
            }    
        }catch(Exception e){
            JOptionPane.showMessageDialog(tabbedPane, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void tabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabbedPaneStateChanged
        // TODO add your handling code here:
        displayTable();
    }//GEN-LAST:event_tabbedPaneStateChanged

    private void tblCollegeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCollegeMouseClicked
        // TODO add your handling code here:
        int row = tblCollege.getSelectedRow();
        txtCollegeCode.setText(tblCollege.getValueAt(row, 0).toString());
        txtDescription.setText(tblCollege.getValueAt(row, 1).toString());
        txtActive.setText(tblCollege.getValueAt(row, 2).toString());
        txtDateOpened.setText(tblCollege.getValueAt(row, 3).toString());
        txtDateClosed.setText(tblCollege.getValueAt(row, 4).toString());
    }//GEN-LAST:event_tblCollegeMouseClicked

    private void tblSubjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSubjectMouseClicked
        // TODO add your handling code here:
        int row = tblSubject.getSelectedRow();
        txtSubjectCode.setText(tblSubject.getValueAt(row, 0).toString());
        txtSubDescription.setText(tblSubject.getValueAt(row, 1).toString());
        txtUnits.setText(tblSubject.getValueAt(row, 2).toString());
        txtCollegeCodeFK.setText(tblSubject.getValueAt(row, 3).toString());
        txtSubActive.setText(tblSubject.getValueAt(row, 4).toString());
    }//GEN-LAST:event_tblSubjectMouseClicked

    private void btnCollegeAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCollegeAddMouseClicked
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(tabbedPane, "Do you really want to add?", 
                                                "Add record", JOptionPane.YES_NO_OPTION);
        if(response != 0){
            JOptionPane.showMessageDialog(tabbedPane, "Addition of record aborted", 
                                            "Abort", JOptionPane.YES_NO_OPTION);
            return;
        }
        try{
            ps = conn.prepareStatement("INSERT INTO COLLEGE "
                                     + "VALUES(?, ?, ?, ?, ?)");
            ps.setString(1, txtCollegeCode.getText());
            ps.setString(2, txtDescription.getText());
            ps.setString(3, txtActive.getText().toUpperCase());
            ps.setDate(4, Date.valueOf(txtDateOpened.getText()));
            ps.setDate(5, Date.valueOf(txtDateClosed.getText()));
            ps.executeUpdate();
        }catch(Exception e){
            JOptionPane.showMessageDialog(tabbedPane, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCollegeAddMouseClicked

    private void btnSubAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubAddMouseClicked
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(tabbedPane, "Do you really want to add?", 
                                                "Add record", JOptionPane.YES_NO_OPTION);
        if(response != 0){
            JOptionPane.showMessageDialog(tabbedPane, "Addition of record aborted", 
                                            "Abort", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        try{
            ps = conn.prepareStatement("INSERT INTO SUBJECT "
                                    + "VALUES(?, ?, ?, ?, ?)");
            ps.setString(1, txtSubjectCode.getText());
            ps.setString(2, txtSubDescription.getText());
            ps.setInt(3, Integer.valueOf(txtUnits.getText()));
            ps.setString(4, txtCollegeCodeFK.getText());
            ps.setString(5, txtActive.getText().toUpperCase());
            ps.executeUpdate();
        }catch(Exception e){
            JOptionPane.showMessageDialog(tabbedPane, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSubAddMouseClicked

    private void btnCollegeUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCollegeUpdateMouseClicked
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(tabbedPane, "Do you really want to update?", 
                                                "Update record", JOptionPane.YES_NO_OPTION);
        if(response != 0){
            JOptionPane.showMessageDialog(tabbedPane, "Update of record aborted", 
                                            "Abort", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        try{
            ps = conn.prepareStatement("UPDATE COLLEGE "
                                       + "SET DESCRIPTION = ?, ACTIVE = ?, DATE_OPENED = ?, DATE_CLOSED = ? "
                                       + "WHERE COLLEGE_CODE = ?");
            ps.setString(1, txtDescription.getText());
            ps.setString(2, txtActive.getText().toUpperCase());
            ps.setDate(3, Date.valueOf(txtDateOpened.getText()));
            ps.setDate(4, Date.valueOf(txtDateClosed.getText()));
            ps.setString(5, txtCollegeCode.getText());
            ps.executeUpdate();
        }catch (Exception e){
            JOptionPane.showMessageDialog(tabbedPane, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCollegeUpdateMouseClicked

    private void btnSubUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubUpdateMouseClicked
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(tabbedPane, "Do you really want to update?", 
                                                "Update record", JOptionPane.YES_NO_OPTION);
        if(response != 0){
            JOptionPane.showMessageDialog(tabbedPane, "Update of record aborted", 
                                            "Abort", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        try{
            ps = conn.prepareStatement("UPDATE SUBJECT "
                                       + "SET DESCRIPTION = ?, UNITS = ?, COLLEGE_CODE = ?, ACTIVE = ? "
                                       + "WHERE SUBJECT_CODE = ?");
            ps.setString(1, txtSubDescription.getText());
            ps.setInt(2, Integer.valueOf(txtUnits.getText()));
            ps.setString(3, txtCollegeCodeFK.getText());
            ps.setString(4, txtSubActive.getText().toUpperCase());
            ps.setString(5, txtSubjectCode.getText());
            ps.executeUpdate();
        }catch (Exception e){
            JOptionPane.showMessageDialog(tabbedPane, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSubUpdateMouseClicked

    private void btnCollegeDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCollegeDeleteMouseClicked
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(tabbedPane, "Do you really want to delete?", 
                                                "Delete record", JOptionPane.YES_NO_OPTION);
        if(response != 0){
            JOptionPane.showMessageDialog(tabbedPane, "Deletion of record aborted", 
                                            "Abort", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        try{
            ps = conn.prepareStatement("DELETE FROM COLLEGE "
                                        + "WHERE COLLEGE_CODE = ?");
            ps.setString(1, txtCollegeCode.getText());
            ps.executeUpdate();
            
            clearCollegeTextFields();
        }catch (Exception e){
            JOptionPane.showMessageDialog(tabbedPane, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCollegeDeleteMouseClicked
    private void clearCollegeTextFields(){
        txtCollegeCode.setText("");
        txtDescription.setText("");
        txtActive.setText("");
        txtDateOpened.setText("");
        txtDateClosed.setText("");
    }
    private void clearSubTextFields(){
        txtSubjectCode.setText("");
        txtSubDescription.setText("");
        txtUnits.setText("");
        txtCollegeCodeFK.setText("");
        txtSubActive.setText("");
    }
    private void btnSubDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubDeleteMouseClicked
        // TODO add your handling code here:
         int response = JOptionPane.showConfirmDialog(tabbedPane, "Do you really want to delete?", 
                                                "Delete record", JOptionPane.YES_NO_OPTION);
        if(response != 0){
            JOptionPane.showMessageDialog(tabbedPane, "Deletion of record aborted", 
                                            "Abort", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        try{
            ps = conn.prepareStatement("DELETE FROM SUBJECT "
                                            + "WHERE SUBJECT_CODE = ?");
            ps.setString(1, txtSubjectCode.getText());
            ps.executeUpdate();
            
            clearSubTextFields();
        }catch (Exception e){
            JOptionPane.showMessageDialog(tabbedPane, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSubDeleteMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        displayTable();
    }//GEN-LAST:event_formWindowActivated

    private void btnSubClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubClearMouseClicked
        // TODO add your handling code here:
        clearSubTextFields();
    }//GEN-LAST:event_btnSubClearMouseClicked

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        // TODO add your handling code here:
        clearCollegeTextFields();
    }//GEN-LAST:event_btnClearMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCollegeAdd;
    private javax.swing.JButton btnCollegeDelete;
    private javax.swing.JButton btnCollegeUpdate;
    private javax.swing.JButton btnSubAdd;
    private javax.swing.JButton btnSubClear;
    private javax.swing.JButton btnSubDelete;
    private javax.swing.JButton btnSubUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblActive;
    private javax.swing.JLabel lblCollegeCode;
    private javax.swing.JLabel lblCollegeCodeFK;
    private javax.swing.JLabel lblDateClosed;
    private javax.swing.JLabel lblDateOpened;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblSubActive;
    private javax.swing.JLabel lblSubDescription;
    private javax.swing.JLabel lblSubjectCode;
    private javax.swing.JLabel lblUnits;
    private javax.swing.JPanel panelCollege;
    private javax.swing.JPanel panelSubject;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTable tblCollege;
    private javax.swing.JTable tblSubject;
    private javax.swing.JTextField txtActive;
    private javax.swing.JTextField txtCollegeCode;
    private javax.swing.JTextField txtCollegeCodeFK;
    private javax.swing.JTextField txtDateClosed;
    private javax.swing.JTextField txtDateOpened;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtSubActive;
    private javax.swing.JTextField txtSubDescription;
    private javax.swing.JTextField txtSubjectCode;
    private javax.swing.JTextField txtUnits;
    // End of variables declaration//GEN-END:variables
}
